# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4043ed8acd6e6aaa83ad134a9162d86af8e7a2364a40e69ce7e449cc6c34c714041cef2ab807b86cc4fdbf28bc1d044c6e79306bbe2609ba7d6071d30a0faf0

test:
  secret_key_base: a9b1088e726a5bce960104e77b047609df1640101bd43da109fce9eb660150fd380706ad1ca48968cee2cec3afc1dca0023434d6cbea559d2111c826e0eddeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
